version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "petfind2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s5f1dyujr204"
s3_prefix = "petfind2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
